services:
  retronova-backoffice:
    build:
      context: .
      dockerfile: Dockerfile
    image: retronova-backoffice:latest
    container_name: retronova-backoffice-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logs configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Security options
    security_opt:
      - no-new-privileges:true

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  default:
    name: retronova-network
